PACKAGE_VERSION="5.20.28"

# Items below here should not have to change with each driver version
PACKAGE_NAME="igb"

BUILT_MODULE_NAME[0]="igb"

BUILT_MODULE_LOCATION[0]="src/"

DEST_MODULE_LOCATION[0]="/kernel/drivers/net/igb"

MAKE[0]="make -C src KSP=$kernel_source_dir MANDIR=%{_mandir}"

CLEAN="make -C src clean"

MODULES_CONF_ALIAS_TYPE="eth"

MODULES_CONF_OBSOLETE_ONLY="yes"

AUTOINSTALL="no"

REMAKE_INITRD="no"
